server:
  port: 8080

server.port.http: 8080

photo:
  output-dir: "/home/lunias/Pictures/photo/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      # location: /tmp/uploads
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:file:~/photodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop #update
    properties.hibernate.format_sql: false
  boot:
    admin:
      client:
        url: "http://localhost:8082"
        username: admin
        password: admin

logging:
  file: "/var/log/photo.log"
  pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org:
      hibernate:
        sql: debug
        # type: trace
