photo:
  output-dir: "/home/lunias/Pictures/photo/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      # location: /tmp/uploads
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:file:~/photodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.hibernate.ddl-auto: update
  boot:
    admin:
      client:
        url: "http://localhost:8082"
        username: admin
        password: admin

logging:
  file: "/var/log/photo.log"
  pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

# show sql statements
# logging.level.org.hibernate.SQL: debug
