spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:h2:file:~/photodb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa.hibernate.ddl-auto: update

# show sql statements
# logging.level.org.hibernate.SQL: debug
